### ISSUE TITLE
Aadhaar Verification Api

### ISSUE THREAD

**Issue by sharmitha35** [dhruv2185/fliphealth#2]
react-dom.development.js:86 Warning: React does not recognize the `helperText` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `helpertext` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at http://localhost:3000/static/js/bundle.js:17460:66
    at InputBase (http://localhost:3000/static/js/bundle.js:30280:83)
    at OutlinedInput (http://localhost:3000/static/js/bundle.js:34090:82)
    at http://localhost:3000/static/js/bundle.js:17460:66
    at Select (http://localhost:3000/static/js/bundle.js:35452:82)
    at div
    at http://localhost:3000/static/js/bundle.js:17460:66
    at FormControl (http://localhost:3000/static/js/bundle.js:27793:82)
    at form
    at http://localhost:3000/static/js/bundle.js:17460:66
    at Box (http://localhost:3000/static/js/bundle.js:43873:72)
    at div
    at http://localhost:3000/static/js/bundle.js:17460:66
    at Box (http://localhost:3000/static/js/bundle.js:43873:72)
    at main
    at http://localhost:3000/static/js/bundle.js:17460:66
    at Container (http://localhost:3000/static/js/bundle.js:42757:19)
    at PatientLogin (http://localhost:3000/static/js/bundle.js:6118:66)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:101605:5)
    at Routes (http://localhost:3000/static/js/bundle.js:102296:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:42365:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:43127:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:40791:14)
    at App (http://localhost:3000/static/js/bundle.js:57:77)
    at Router (http://localhost:3000/static/js/bundle.js:102230:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:100202:5)
    at SnackbarProvider (http://localhost:3000/static/js/bundle.js:68055:24)
    at Provider (http://localhost:3000/static/js/bundle.js:97296:3)
printWarning @ react-dom.development.js:86

AbiError: Parameter decoding error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
    at decodeParametersWith (parameters_api.ts:109:1)
    at decodeParameters (parameters_api.ts:219:1)
    at decodeMethodReturn (encoding.ts:174:1)
    at ContractBuilder.<anonymous> (contract.ts:1167:1)
    at Generator.next (<anonymous>)
    at fulfilled (contract.ts:1:1) Getting error like this

**Comment by dhruv2185** [comment]
Did you set up everything correctly, also please refer the .env.example file and set those variables as per your needs.

**Comment by sharmitha35** [comment]
.env
REACT_APP_PROJECT_ID = "4c46604b23e74da9b9d510bc5b425265"
REACT_APP_PROJECT_KEY = "c4OAxcwZdWa+H4yf/gosKg8Hhg+sQmFdjaX6oJyMgy4IU9ad4++hjg"
REACT_APP_BLOCKCHAIN_PROVIDER_URL = "http://localhost:7545"
REACT_APP_HOSPITAL_CONTRACT_ADDRESS = "0x0F2FaD18F686d30D888CD6765c5FCE7A427196e4"
REACT_APP_SANDBOX_API_KEY= "k9F35K3NTNEz19mwCOeMeZ32tK4CHA0g"
REACT_APP_SANDBOX_API_SECRET= "8-iWj3twmLx2LqWH65tps8wjUxxIYmrrMt2eKQxffXVB2J30u_GiBj0ypDgLukaJ"
REACT_APP_AADHAR_VERIFICATION_URL = "https://myaadhaar.uidai.gov.in/offline-ekyc".Is the above urls correct

**Comment by dhruv2185** [comment]
No, here we are not using the uidai credentials, we had subscribed to sandbox's aadhar API, and also had set up a proxy server as mentioned in the readme file. It is relatively complex to setup this application on the localhost as it involves different apis'. Please first try to use the deployed version and get familiar.

**Comment by sharmitha35** [comment]
proxy server url is not working.how to set up a proxy server url
